### ISSUE TITLE
Declare your website as safe website

### ISSUE THREAD

**Issue by heurteph-ei** [Findus23/lw1.at#2]
🇦🇹Hallo🇦🇹 Lukas,

When I browse your website from my company, its access is prevented because your website hasn't been referenced as safe by Symantec.
Could you declare it at: https://sitereview.bluecoat.com/#/lookup-result/lw1.at

Regards

**Comment by Findus23** [comment]
Hi,

Thanks for the notice. I am totally not familiar with those company web filters, so what would you recommend should I select in this form?
Does this also cascade to subdomains? (So if I submit lw1.at as a personal site, will the filter potentially also block https://guides.lw1.at/ as "non-productive"?

**Comment by heurteph-ei** [comment]
Personal seems to be good.
I am not sure about the cascade. What I know is:
- `http://translate.google.com/` is categorized as **Translation**
- `http://mail.google.com/` is categorized as **Email**
- `http://google.com/` is categorized as **Search Engines/Portals**

**Comment by Findus23** [comment]
And which filtering service should I pick? I can only choose one apparently...

**Comment by heurteph-ei** [comment]
Not idea... I would say, maybe Blue Coat ProxySG? (as I already asked in the past for a Matomo site here: https://forum.matomo.org/t/images-from-matomo-blog-are-blacklisted-by-our-company-due-to-not-registered-by-symantec/43429 )

**Comment by Findus23** [comment]
Okay, done :heavy_check_mark: 
I used Personal Site and Technology/Internet (as the latter is also apparently how matomocamp.org and matomo.org are categorized).
I'll report back any response I get

**Comment by Findus23** [comment]
> Based on your recommendation and after careful evaluation of the Web content submitted, a Web Content Analyst has categorized this URL as [Technology/Internet](https://sitereview.symantec.com/#/category-descriptions/38).

Guess that's it.
Thanks again for the notice!

**Comment by heurteph-ei** [comment]
I just checked and it works.
Thanks :-)
